# Schema for the configuration files of the lagoon_logs module.

lagoon_logs.settings:
  type: config_object
  label: 'Lagoon logs settings'
  mapping:
    disable:
      type: integer
      label: 'Disabled'
    host:
      type: string
      label: 'Logstash host'
    port:
      type: integer
      label: 'Logstash port'
    identifier:
      type: string
      label: 'Logstash leading identifier'
